-- AlterTable
ALTER TABLE "MonthlyPayroll" ADD COLUMN IF NOT EXISTS "paidLeaves" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MonthlyPayroll" ADD COLUMN IF NOT EXISTS "lateFines" DOUBLE PRECISION NOT NULL DEFAULT 0;
