'use client'

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { useQuery } from '@tanstack/react-query'
import { apiGet } from '@/lib/api-client'
import { FileText, ExternalLink } from 'lucide-react'
import { format } from 'date-fns'
import { useRouter } from 'next/navigation'

interface EmployeeDocument {
  id: string
  documentType: 'OFFER_LETTER' | 'APPRAISAL_LETTER' | 'EXPERIENCE_LETTER' | 'RELIEVING_LETTER'
  generatedAt: string
}

const DOCUMENT_TYPES = {
  OFFER_LETTER: 'Offer Letter',
  APPRAISAL_LETTER: 'Appraisal Letter',
  EXPERIENCE_LETTER: 'Experience Letter',
  RELIEVING_LETTER: 'Relieving Letter',
}

export default function EmployeeDocumentsPage() {
  const router = useRouter()

  const { data: documents, isLoading } = useQuery<EmployeeDocument[]>({
    queryKey: ['my-documents'],
    queryFn: () => apiGet<EmployeeDocument[]>('/api/employee/documents'),
  })

  const handleViewDocument = (docId: string) => {
    router.push(`/employee/documents/${docId}/view`)
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">My Documents</h1>
        <p className="text-muted-foreground mt-1">View and download your employment documents</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Employment Documents
          </CardTitle>
          <CardDescription>
            Documents generated by HR for your employment records - click View & Download to preview and save as PDF
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="text-center py-8 text-muted-foreground">Loading...</div>
          ) : documents && documents.length > 0 ? (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Document Type</TableHead>
                  <TableHead>Generated On</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {documents.map((doc) => (
                  <TableRow key={doc.id}>
                    <TableCell>
                      <Badge variant="secondary">
                        {DOCUMENT_TYPES[doc.documentType]}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      {format(new Date(doc.generatedAt), 'PPP')}
                    </TableCell>
                    <TableCell>
                      <Button
                        variant="default"
                        size="sm"
                        onClick={() => handleViewDocument(doc.id)}
                      >
                        <ExternalLink className="h-4 w-4 mr-1" />
                        View & Download
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          ) : (
            <div className="text-center py-12 text-muted-foreground">
              <FileText className="h-12 w-12 mx-auto mb-4 opacity-50" />
              <p>No documents available yet</p>
              <p className="text-sm mt-1">Documents will appear here once HR generates them for you</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}

